import { AuthProvider } from "./Providers";
import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth/next";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
   const session = await getServerSession()

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider session={session}>
          {children}  
        </AuthProvider>
      </body>
    </html>
  );
}
